name: Merge any release branch to uat
on:
  push:
    branches: ["automerge_poc"]
    
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> beta
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}