# We are using Playwright but you may use your E2E framework of choice
name: Playwright Tests

on:
  deployment_status:
    
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: "echo ${{ github.event }}""