# We are using Playwright but you may use your E2E framework of choice
name: Playwright Tests

on:
  deployment_status:
    
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo "${{github.event.deployment_status}}""
      run: npm ci
    - name: Run tests
      run: npm run cypress
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}