# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Test Integration Branch

on:
  push:
    branches: [ "integration_poc" ]

jobs:
  wait-for-vercel-deployment:

    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Retrieve deployment URL (example on how to set an ENV var)
      uses: UnlyEd/github-action-await-vercel@v1.2.39
      id: await-vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      with:
        deployment-url: "https://preview-from-integration-poc.vercel.app"
        timeout: 60 # Wait for 10 seconds before failing

    - name: Displays the deployment name (example on how to read information about the deployment)
      run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"    
  
