name: 'Run Cypress test'
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "${{github.event.deployment}}"