name: ci/cd fix -1 
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment URL
        run: echo "${{ github.event.deployment_status.target_url }}"
      - name: Checkout  
        uses: actions/checkout@v3 
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          wait-on: ${{ github.event.deployment_status.target_url }}
          spec: cypress/e2e/**/*.cy.ts
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}  