name: Sync multiple branches

on:
  push:
    branches: ["automerge_poc"]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge automerge_poc -> beta
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: automerge_poc
          target_branch: beta
          github_token: ${{ secrets.GIT_SECRET }}
